name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: basic run test
      id: basic-run-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: basic run test
        setup-command: chmod +x ./Setup/setup.sh; ./Setup/setup.sh programmingIsFun;
          chmod +x ./Test/run.sh;
        command: "./Test/run.sh"
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BASIC-RUN-TEST_RESULTS: "${{steps.basic-run-test.outputs.result}}"
      with:
        runners: basic-run-test
